### ISSUE TITLE
Failed to shutdown when alone in network

### ISSUE THREAD

**Issue by SuperiorNiels** [SuperiorNiels/SystemY#3]
when alone in the network the node fails to shutdown, error thrown from line 303 in fileManager

**Comment by Dieter97** [comment]
@SuperiorNiels I know, i just found the same bug with 3 nodes in the network. For the bug with 3 nodes I think this is because the entries are not placed on the correct node in updateFilesNewNode.
For the bug with 1 node the fix is easy, just don't run the code when alone in network 👍

**Comment by Dieter97** [comment]
I fixed it and pushed it to master 💃

**Comment by SuperiorNiels** [comment]
Pure cringe dees
